
CREATE TABLE IF NOT EXISTS meals
(
    id TEXT UNIQUE NOT NULL,
    user_chat_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    calories INTEGER NOT NULL,
    consumed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    chat_id INTEGER UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(chat_id)
);